const ADD_LIST_ITEM = "ADD_LIST_ITEM";
const DEL_LIST_ITEM = "DEL_LIST_ITEM";
const EDIT_LIST_ITEM = "EDIT_LIST_ITEM";
const MARK_LIST_ITEM = "MARK_LIST_ITEM";
const DONE_ITEM = "DONE_ITEM";

module.exports = {
    ADD_LIST_ITEM,
    DEL_LIST_ITEM,
    EDIT_LIST_ITEM,
    MARK_LIST_ITEM,
    DONE_ITEM
};