const ADD_LIST_ITEM = "ADD_LIST_ITEM";
const DEL_LIST_ITEM = "DEL_LIST_ITEM";
const EDIT_LIST_ITEM = "EDIT_LIST_ITEM";
const MARK_LIST_ITEM = "MARK_LIST_ITEM";
const FILTER_LIST_ITEMS = "FILTER_LIST_ITEMS"

module.exports = {
    ADD_LIST_ITEM,
    DEL_LIST_ITEM,
    EDIT_LIST_ITEM,
    MARK_LIST_ITEM,
    FILTER_LIST_ITEMS
};